# `EDA on Insurance Claim Dataset:`

## `Notebook Overview:`

In this notebook, we will take a closer look at Insurance Claims and figure out some facts about how conditions such as blood pressure, BMI, diabetes, smoking, age, and gender impact the claim value.

We will touch the topics through exploratory data analysis (EDA) using scatter plots, pie charts, histograms etc.

In [1]:
# importing necessary libraries
import numpy as np    # for linear algebra
import pandas as pd   # for reading data files
import matplotlib.pyplot as plt  # for making graphs
%matplotlib inline
import seaborn as sns  # another library for making graphs

In [2]:
# reading the csv file
df_ins = pd.read_csv('insurance_data.csv')

## `Data Processing and Data Preparation:`

In [3]:
# checking the dataset content
df_ins.head()

,index,PatientID,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,0,1,39.0,male,23.2,91,Yes,0,No,southeast,1121.87
1,1,2,24.0,male,30.1,87,No,0,No,southeast,1131.51
2,2,3,NaN,male,33.3,82,Yes,0,No,southeast,1135.94
3,3,4,NaN,male,33.7,80,No,0,No,northwest,1136.40
4,4,5,NaN,male,34.1,100,No,0,No,northwest,1137.01

In [4]:
# checking the rows and cols of the dataset
rows = df_ins.shape[0]
cols = df_ins.shape[1]
print(f'The insurance claim dataset contains {rows} rows and {cols} cols')

The insurance claim dataset contains 1340 rows and 11 cols

In [5]:
# data types + non-null counts for every column
df_ins.info()

<class 'pandas.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          1340 non-null   int64
 1   PatientID      1340 non-null   int64
 2   age            1335 non-null   float64
 3   gender         1340 non-null   str
 4   bmi            1340 non-null   float64
 5   bloodpressure  1340 non-null   int64
 6   diabetic       1340 non-null   str
 7   children       1340 non-null   int64
 8   smoker         1340 non-null   str
 9   region         1337 non-null   str
 10  claim          1340 non-null   float64
dtypes: float64(3), int64(4), str(4)
memory usage: 115.3 KB

In [6]:
# finding which cols have null values
df_ins.isna().sum()

index            0
PatientID        0
age              5
gender           0
bmi              0
bloodpressure    0
diabetic         0
children         0
smoker           0
region           3
claim            0
dtype: int64

> This shows the our age col and region col have null values we need to handle them safely.

In [ ]:
num_cols = df_ins.select_dtypes(include="number").columns   # separating numerical col from categorical col

df = df_ins.copy()
df[num_cols] = df[num_cols].interpolate()   # use to fill the nan value in the numerical col

df = df.fillna(df.mode().iloc[0])

df.isna().sum()

index            0
PatientID        0
age              0
gender           0
bmi              0
bloodpressure    0
diabetic         0
children         0
smoker           0
region           0
claim            0
dtype: int64

In [10]:
# getting a deeper look in the dataset
df.describe().round(0)

        index  PatientID     age     bmi  bloodpressure  children    claim
count  1340.0     1340.0  1340.0  1340.0         1340.0    1340.0   1340.0
mean    670.0      670.0    38.0    31.0           94.0       1.0  13253.0
std     387.0      387.0    11.0     6.0           11.0       1.0  12110.0
min       0.0        1.0    18.0    16.0           80.0       0.0   1122.0
25%     335.0      336.0    29.0    26.0           86.0       0.0   4720.0
50%     670.0      670.0    37.0    30.0           92.0       1.0   9370.0
75%    1004.0     1005.0    47.0    35.0           99.0       2.0  16604.0
max    1339.0     1340.0    60.0    53.0          140.0       5.0  63770.0

In [13]:
# checking for the categorical col and there values in dataset
for col in df.columns:
    if df[col].dtype == 'str':
        print(col)
        print(df[col].unique())
        print()

gender
<StringArray>
['male', 'female']
Length: 2, dtype: str

diabetic
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

smoker
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

region
<StringArray>
['southeast', 'northwest', 'southwest', 'northeast']
Length: 4, dtype: str

In [14]:
# replacing the diabetic and smoker col appropriately using replace for better understanding
df['diabetic'] = df['diabetic'].replace({'Yes': 'diabetic', 'No': 'non-diabetic'})
df['smoker'] = df['smoker'].replace({'Yes': 'smoker', 'No': 'non-smoker'})

In [15]:
df

,index,PatientID,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,0,1,39.000000,male,23.2,91,diabetic,0,non-smoker,southeast,1121.87
1,1,2,24.000000,male,30.1,87,non-diabetic,0,non-smoker,southeast,1131.51
2,2,3,23.166667,male,33.3,82,diabetic,0,non-smoker,southeast,1135.94
3,3,4,22.333333,male,33.7,80,non-diabetic,0,non-smoker,northwest,1136.40
4,4,5,21.500000,male,34.1,100,non-diabetic,0,non-smoker,northwest,1137.01
...,...,...,...,...,...,...,...,...,...,...,...
1335,1335,1336,44.000000,female,35.5,88,diabetic,0,smoker,northwest,55135.40
1336,1336,1337,59.000000,female,38.1,120,non-diabetic,1,smoker,northeast,58571.07
1337,1337,1338,30.000000,male,34.5,91,diabetic,3,smoker,northwest,60021.40
1338,1338,1339,37.000000,male,30.4,106,non-diabetic,0,smoker,southeast,62592.87
1339,1339,1340,30.000000,female,47.4,101,non-diabetic,0,smoker,southeast,63770.43

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          1340 non-null   int64
 1   PatientID      1340 non-null   int64
 2   age            1340 non-null   float64
 3   gender         1340 non-null   str
 4   bmi            1340 non-null   float64
 5   bloodpressure  1340 non-null   int64
 6   diabetic       1340 non-null   str
 7   children       1340 non-null   int64
 8   smoker         1340 non-null   str
 9   region         1340 non-null   str
 10  claim          1340 non-null   float64
dtypes: float64(3), int64(4), str(4)
memory usage: 115.3 KB

> Every null value is maintained safely and we have a breif overview about the data we are working on.

## `Exploratory Data Analysis (EDA):`