## `What is Data Analysis:`

> Data analysis is the process of inspecting, cleansing, tranforming and modeling data with the goal of discovering usedful information, informing conclusion and supporting decision-making.

## `Data Analysis Process:`

Data is analyzed in 5 steps which are as follow:

1. **Asking Questions:** 
Asking right question like what is the data about why we need such data what we can do with this data.

2. **Data Preprocessing:**
The data we get is messy we can not use it for getting a meaningful result in order to achieve it we need to clean the data and then use it for analysis.

3. **Exploratory Data Analysis(EDA):**
Once we have cleaned our data we do exploration.  Analyzing the data through statistical summaries and visual graphs (histograms, scatter plots, etc.) to understand relationships.
Improving the data to facilitate better insights, which includes removing outliers and feature engineering (creating new columns or transforming existing ones).

4. **Drawing Conclusions:**
Using the insights gained, you draw conclusions or make predictions. This often involves Machine Learning algorithms or Inferential Statistics to make predictions about a larger population based on a sample.

5. **Communicating Results:**
The final step is effectively communicating your findings. It’s about translating technical analysis into actionable insights that can support business decision-making.

## `Working with csv file:`

### `1. Importing Pandas:`

In [1]:
import pandas as pd

### `2. Opening local csv file:`

In [8]:
train_df = pd.read_csv('E:/ai-learning/data/Data for week-2/aug_train.csv')
train_df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

### `3. Opening a csv file from an URL:`

In [4]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

### `4. Sep Parameter:`

In [7]:
pd.read_csv('E:/ai-learning/data/Data for week-2/movie_titles_metadata.tsv', sep='\t',names=['sr', 'movie_name', 'release_year', 'rating', 'votes', 'genre'])

,sr,movie_name,release_year,rating,votes,genre
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

### `5. index_col Parameter:`

In [10]:
pd.read_csv('E:/ai-learning/data/Data for week-2/aug_train.csv', index_col='enrollee_id')

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

### `6. Header Parameter:`

In [13]:
pd.read_csv('E:/ai-learning/data/Data for week-2/test.csv', header=1)

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
1,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
2,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
3,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

### `7. use_col parameter:`

In [14]:
pd.read_csv('E:/ai-learning/data/Data for week-2/aug_train.csv', usecols= ['enrollee_id', 'gender', 'education_level'])

       enrollee_id gender education_level
0             8949   Male        Graduate
1            29725   Male        Graduate
2            11561    NaN        Graduate
3            33241    NaN        Graduate
4              666   Male         Masters
...            ...    ...             ...
19153         7386   Male        Graduate
19154        31398   Male        Graduate
19155        24576   Male        Graduate
19156         5756   Male     High School
19157        23834    NaN  Primary School

[19158 rows x 3 columns]

### `8. Skiprows/nrows Parameter:`

In [17]:
pd.read_csv('E:/ai-learning/data/Data for week-2/aug_train.csv', skiprows=[0,1])

,29725,city_40,0.7759999999999999,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
0,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
1,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
2,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
3,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
4,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19151,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19152,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19153,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19154,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19155,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [18]:
pd.read_csv('E:/ai-learning/data/Data for week-2/aug_train.csv', nrows=100)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,12081,city_65,0.802,Male,Has relevent experience,Full time course,Graduate,STEM,9,50-99,Pvt Ltd,1,33,0.0
96,7364,city_160,0.920,NaN,No relevent experience,Full time course,High School,NaN,2,100-500,Pvt Ltd,1,142,0.0
97,11184,city_74,0.579,NaN,No relevent experience,Full time course,Graduate,STEM,2,100-500,Pvt Ltd,1,34,0.0
98,7016,city_65,0.802,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,50-99,Pvt Ltd,2,14,1.0
99,8695,city_11,0.550,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,10/49,Pvt Ltd,2,27,1.0

### `9. Encoding Parameter:`

In [27]:
pd.read_csv('E:/ai-learning/data/Data for week-2/zomato.csv', encoding='latin-1')

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ÛÁstanbul,"Kemankeô Karamustafa Paôa Mahallesi, RÛ±htÛ±...",Karakí_y,"Karakí_y, ÛÁstanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz AÛôacÛ±,208,ÛÁstanbul,"Koôuyolu Mahallesi, Muhittin íìstí_ndaÛô Cadd...",Koôuyolu,"Koôuyolu, ÛÁstanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aôôk Kahve,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ÛÁstanbul,"CafeaÛôa Mahallesi, BademaltÛ± Sokak, No 21/B,...",Moda,"Moda, ÛÁstanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

### `10. dtypes parameter:`

In [30]:
pd.read_csv('E:/ai-learning/data/Data for week-2/aug_train.csv', dtype={'target':int})

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0

### `11. Handling Dates:`

In [33]:
pd.read_csv('E:/ai-learning/data/Data for week-2/IPL Matches 2008-2020.csv', parse_dates=['date']).info()

<class 'pandas.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    str
 2   date             816 non-null    datetime64[us]
 3   player_of_match  812 non-null    str
 4   venue            816 non-null    str
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    str
 7   team2            816 non-null    str
 8   toss_winner      816 non-null    str
 9   toss_decision    816 non-null    str
 10  winner           812 non-null    str
 11  result           812 non-null    str
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    str
 14  method           19 non-null     str
 15  umpire1          816 non-null    str
 16  umpire2          816 non-null    str
dtypes: datetime64[us](1), float64(1), int64(2), str(13)
memory usage: 108.5 KB

### `12. Converters:`

In [46]:
def name_converter(team):
    words = team.split()
    short_name = ''

    for word in words:
        short_name += word[0].upper()
    return short_name

In [48]:
pd.read_csv('E:/ai-learning/data/Data for week-2/IPL Matches 2008-2020.csv', converters=({'team1': name_converter, 'team2': name_converter}))

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,RCB,KKR,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,KXP,CSK,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,DD,RR,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,MI,RCB,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,KKR,DC,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,RCB,MI,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,MI,DC,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,RCB,SH,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,DC,SH,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,DC,MI,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

### `13. na_values parameter:`

In [50]:
pd.read_csv('E:/ai-learning/data/Data for week-2/aug_train.csv', na_values=['Male'])

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,NaN,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,NaN,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,NaN,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,NaN,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In order to export the csv file we only need to write:
> **pd.to_csv()**

## `Working with exel file:`

As we use a function name `read_csv` to read csv files we can use a function named `read_excel` to gather data form excel

## `Wokring with API:`

In [1]:
import pandas as pd
import requests

In [21]:
response = requests.get('https://api.tvmaze.com/shows')

In [22]:
df = pd.DataFrame(response.json())
df = df.set_index('id')
df

,url,name,type,language,genres,status,runtime,averageRuntime,premiered,ended,...,rating,weight,network,webChannel,dvdCountry,externals,image,summary,updated,_links
id,,,,,,,,,,,,,,,,,,,,,
1,https://www.tvmaze.com/shows/1/under-the-dome,Under the Dome,Scripted,English,"[Drama, Science-Fiction, Thriller]",Ended,60.0,60,2013-06-24,2015-09-10,...,{'average': 6.6},98,"{'id': 2, 'name': 'CBS', 'country': {'name': '...",None,None,"{'tvrage': 25988, 'thetvdb': 264492, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p><b>Under the Dome</b> is the story of a sma...,1769177765,{'self': {'href': 'https://api.tvmaze.com/show...
2,https://www.tvmaze.com/shows/2/person-of-interest,Person of Interest,Scripted,English,"[Action, Crime, Science-Fiction]",Ended,60.0,60,2011-09-22,2016-06-21,...,{'average': 8.8},99,"{'id': 2, 'name': 'CBS', 'country': {'name': '...",None,None,"{'tvrage': 28376, 'thetvdb': 248742, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>You are being watched. The government has a...,1783133158,{'self': {'href': 'https://api.tvmaze.com/show...
3,https://www.tvmaze.com/shows/3/bitten,Bitten,Scripted,English,"[Drama, Horror, Romance]",Ended,60.0,60,2014-01-11,2016-04-15,...,{'average': 7.4},94,"{'id': 7, 'name': 'CTV Sci-Fi Channel', 'count...",None,None,"{'tvrage': 34965, 'thetvdb': 269550, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>Based on the critically acclaimed series of...,1704793709,{'self': {'href': 'https://api.tvmaze.com/show...
4,https://www.tvmaze.com/shows/4/arrow,Arrow,Scripted,English,"[Drama, Action, Science-Fiction]",Ended,60.0,60,2012-10-10,2020-01-28,...,{'average': 7.4},99,"{'id': 5, 'name': 'The CW', 'country': {'name'...",None,None,"{'tvrage': 30715, 'thetvdb': 257655, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,"<p>After a violent shipwreck, billionaire play...",1766868900,{'self': {'href': 'https://api.tvmaze.com/show...
5,https://www.tvmaze.com/shows/5/true-detective,True Detective,Scripted,English,"[Drama, Crime, Thriller]",Running,60.0,63,2014-01-12,NaN,...,{'average': 8.1},100,"{'id': 8, 'name': 'HBO', 'country': {'name': '...",None,None,"{'tvrage': 31369, 'thetvdb': 270633, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>Touch darkness and darkness touches you bac...,1777231753,{'self': {'href': 'https://api.tvmaze.com/show...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,https://www.tvmaze.com/shows/245/town-of-the-l...,Town of the Living Dead,Reality,English,[],Ended,30.0,30,2014-10-07,2014-11-11,...,{'average': None},43,"{'id': 16, 'name': 'Syfy', 'country': {'name':...",None,None,"{'tvrage': 44602, 'thetvdb': 282253, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,"<p>In <b>Town of the Living Dead</b>, the colo...",1704795205,{'self': {'href': 'https://api.tvmaze.com/show...
246,https://www.tvmaze.com/shows/246/long-shadow,Long Shadow,Documentary,English,"[War, History]",Ended,60.0,60,2014-09-24,2014-10-08,...,{'average': None},34,"{'id': 37, 'name': 'BBC Two', 'country': {'nam...",None,None,"{'tvrage': 44987, 'thetvdb': 286553, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>David Reynolds traces the legacy of the Gre...,1578901625,{'self': {'href': 'https://api.tvmaze.com/show...
247,https://www.tvmaze.com/shows/247/the-colbert-r...,The Colbert Report,Talk Show,English,[Comedy],Ended,30.0,30,2005-10-17,2014-12-18,...,{'average': 7.2},65,"{'id': 23, 'name': 'Comedy Central', 'country'...",None,None,"{'tvrage': 6715, 'thetvdb': 79274, 'imdb': 'tt...",{'medium': 'https://static.tvmaze.com/uploads/...,"<p>Feel the news along with Stephen Colbert, A...",1693353845,{'self': {'href': 'https://api.tvmaze.com/show...
248,https://www.tvmaze.com/shows/248/transporter-t...,Transporter: The Series,Scripted,English,"[Action, Adventure, Crime]",Ended,60.0,60,2013-01-04,2014-12-14,...,{'average': 7.3},80,"{'id': 164, 'name': 'RTL', 'country': {'name':...",None,None,"{'tvrage': 27190, 'thetvdb': 248962, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>Frank Martin returns as the Transporter wit...,1766505449,{'self': {'href': 'https://api.tvmaze.com/show...
249,https://www.tvmaze.com/shows/249/the-daily-sho...,The Daily Show with Jon Stewart,Talk Show,English,[Comedy],Ended,30.0,30,1999-01-11,2015-08-06,...,{'average': 8},93,"{'id': 23, 'name': 'Comedy Central', 'country'...",None,None,"{'tvrage': 5714, 'thetvdb': None, 'imdb': None}",{'medium': 'https://static.tvmaze.com/uploads/...,"<p>One anchor, several correspondents, zero cr...",1715257485,{'self': {'href': 'https://api.tvmaze.com/show...

## `Web Scrapping:`

In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [4]:
import requests

response = requests.get("https://books.toscrape.com/")
response.encoding = "utf-8"

html = response.text

In [5]:
soup = BeautifulSoup(html, 'html.parser')
print(soup.prettify())

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   All products | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:29" name="created"/>
  <meta content="" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="default" id="default">
  <header class="header container-fluid">
   <div class="page_inner">
    <div class="row">
     <div class="col-sm-8 h1">
      <a href="index.html">
       Books to Scrape
      </a>
      <small>
       We love being scraped!
      </small>
     </div>
    </div>
   </div>
  </header>
  <div class="container-fluid page">
   <div class="page_inner">
    <ul class="breadcrumb">
     <li>
      <a href="index.html">
       Home
      </a>
     </li>
     <li class="active">
      All products
     </li>
    </ul>
    <div class="row">
     <aside class="sidebar col-sm-4 col-md-3">
      <div id="promotions_left">
      </div>
      <div class="side_categories">
       <ul class="nav nav-list">
        <li>
         <a href="catalogue/category/books_1/index.html">
          Books
         </a>
         <ul>
          <li>
           <a href="catalogue/category/books/travel_2/index.html">
            Travel
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/mystery_3/index.html">
            Mystery
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical-fiction_4/index.html">
            Historical Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sequential-art_5/index.html">
            Sequential Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/classics_6/index.html">
            Classics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/philosophy_7/index.html">
            Philosophy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/romance_8/index.html">
            Romance
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/womens-fiction_9/index.html">
            Womens Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fiction_10/index.html">
            Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/childrens_11/index.html">
            Childrens
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/religion_12/index.html">
            Religion
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/nonfiction_13/index.html">
            Nonfiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/music_14/index.html">
            Music
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/default_15/index.html">
            Default
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science-fiction_16/index.html">
            Science Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sports-and-games_17/index.html">
            Sports and Games
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/add-a-comment_18/index.html">
            Add a comment
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fantasy_19/index.html">
            Fantasy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/new-adult_20/index.html">
            New Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/young-adult_21/index.html">
            Young Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science_22/index.html">
            Science
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/poetry_23/index.html">
            Poetry
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/paranormal_24/index.html">
            Paranormal
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/art_25/index.html">
            Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/psychology_26/index.html">
            Psychology
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/autobiography_27/index.html">
            Autobiography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/parenting_28/index.html">
            Parenting
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/adult-fiction_29/index.html">
            Adult Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/humor_30/index.html">
            Humor
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/horror_31/index.html">
            Horror
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/history_32/index.html">
            History
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/food-and-drink_33/index.html">
            Food and Drink
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian-fiction_34/index.html">
            Christian Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/business_35/index.html">
            Business
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/biography_36/index.html">
            Biography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/thriller_37/index.html">
            Thriller
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/contemporary_38/index.html">
            Contemporary
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/spirituality_39/index.html">
            Spirituality
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/academic_40/index.html">
            Academic
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/self-help_41/index.html">
            Self Help
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical_42/index.html">
            Historical
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian_43/index.html">
            Christian
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/suspense_44/index.html">
            Suspense
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/short-stories_45/index.html">
            Short Stories
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/novels_46/index.html">
            Novels
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/health_47/index.html">
            Health
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/politics_48/index.html">
            Politics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/cultural_49/index.html">
            Cultural
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/erotica_50/index.html">
            Erotica
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/crime_51/index.html">
            Crime
           </a>
          </li>
         </ul>
        </li>
       </ul>
      </div>
     </aside>
     <div class="col-sm-8 col-md-9">
      <div class="page-header action">
       <h1>
        All products
       </h1>
      </div>
      <div id="messages">
      </div>
      <div id="promotions">
      </div>
      <form class="form-horizontal" method="get">
       <div style="display:none">
       </div>
       <strong>
        1000
       </strong>
       results - showing
       <strong>
        1
       </strong>
       to
       <strong>
        20
       </strong>
       .
      </form>
      <section>
       <div class="alert alert-warning" role="alert">
        <strong>
         Warning!
        </strong>
        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.
       </div>
       <div>
        <ol class="row">
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/a-light-in-the-attic_1000/index.html">
             <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
            </a>
           </div>
           <p class="star-rating Three">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
             A Light in the ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £51.77
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/tipping-the-velvet_999/index.html">
             <img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">
             Tipping the Velvet
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £53.74
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/soumission_998/index.html">
             <img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/soumission_998/index.html" title="Soumission">
             Soumission
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £50.10
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sharp-objects_997/index.html">
             <img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">
             Sharp Objects
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £47.82
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html">
             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>
            </a>
           </div>
           <p class="star-rating Five">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">
             Sapiens: A Brief History ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £54.23
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-requiem-red_995/index.html">
             <img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">
             The Requiem Red
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £22.65
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">
             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">
             The Dirty Little Secrets ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £33.34
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html">
             <img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/>

In [48]:
len(soup.find_all('h3'))

20

In [49]:
book_title = []
for i in soup.find_all('h3'):
    book_title += [i.text]

print(book_title)

['A Light in the ...', 'Tipping the Velvet', 'Soumission', 'Sharp Objects', 'Sapiens: A Brief History ...', 'The Requiem Red', 'The Dirty Little Secrets ...', 'The Coming Woman: A ...', 'The Boys in the ...', 'The Black Maria', 'Starving Hearts (Triangular Trade ...', "Shakespeare's Sonnets", 'Set Me Free', "Scott Pilgrim's Precious Little ...", 'Rip it Up and ...', 'Our Band Could Be ...', 'Olio', 'Mesaerion: The Best Science ...', 'Libertarianism for Beginners', "It's Only the Himalayas"]

In [68]:
prices = []

for p in soup.find_all("p", class_="price_color"):
    price = float(p.text.replace("£", ""))
    prices.append(price)

print(prices)

[51.77, 53.74, 50.1, 47.82, 54.23, 22.65, 33.34, 17.93, 22.6, 52.15, 13.99, 20.66, 17.46, 52.29, 35.02, 57.25, 23.88, 37.59, 51.33, 45.17]

In [18]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import time

url = "https://books.toscrape.com/catalogue/page-1.html"
i = 1
books_data = []

while url:

    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f'failed to open: {url}\n{e}' ) 
        break

    response.encoding = 'utf-8'

    html = response.text

    soup = BeautifulSoup(html, 'html.parser')

    books = soup.find_all('article', class_='product_pod')

    for book in books:
        title = book.h3.a['title']

        price = book.find('p', class_='price_color').text.replace('£', '')

        rating = book.find("p", class_="star-rating")["class"][1]

        availability = book.find('p', class_='instock availability').text.strip()

        image_container = book.find('div', class_='image_container')
        image_url = image_container.find('img')['src'] if image_container else 'No image'

        relative_link = book.h3.a['href']
        book_url = urljoin(url, relative_link)

        try:
            book_response = requests.get(book_url, timeout=10)
            book_response.encoding = 'utf-8'

            book_soup = BeautifulSoup(book_response.text, 'html.parser')

            category = book_soup.find('ul', class_='breadcrumb').find_all('li')[2].text.strip()
        except requests.exceptions.RequestException:
            category = None
        books_data.append({
            "title": title,
            "category": category,
            "price": float(price),
            "rating": rating,
            "availability": availability,
            "image_url": image_url
        })
        
        print(f'{i}. ',title, category, price, rating, availability, image_url)
        i += 1
    next_button = soup.find('li', class_='next')

    if next_button:
        next_page_link = next_button.find('a')['href']

        url = urljoin(url, next_page_link)
    else:
        url =None

1.  A Light in the Attic Poetry 51.77 Three In stock ../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg
2.  Tipping the Velvet Historical Fiction 53.74 One In stock ../media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg
3.  Soumission Fiction 50.10 One In stock ../media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg
4.  Sharp Objects Mystery 47.82 Four In stock ../media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg
5.  Sapiens: A Brief History of Humankind History 54.23 Five In stock ../media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg
6.  The Requiem Red Young Adult 22.65 One In stock ../media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg
7.  The Dirty Little Secrets of Getting Your Dream Job Business 33.34 Four In stock ../media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg
8.  The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull Default 17.93 Three In stock ../media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg
9.  The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics Default 22.60 Four In stock ../media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg
10.  The Black Maria Poetry 52.15 One In stock ../media/cache/58/46/5846057e28022268153beff6d352b06c.jpg
11.  Starving Hearts (Triangular Trade Trilogy, #1) Default 13.99 Two In stock ../media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg
12.  Shakespeare's Sonnets Poetry 20.66 Four In stock ../media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg
13.  Set Me Free Young Adult 17.46 Five In stock ../media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg
14.  Scott Pilgrim's Precious Little Life (Scott Pilgrim #1) Sequential Art 52.29 Five In stock ../media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg
15.  Rip it Up and Start Again Music 35.02 Five In stock ../media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg
16.  Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991 Music 57.25 Three In stock ../media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg
17.  Olio Poetry 23.88 One In stock ../media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg
18.  Mesaerion: The Best Science Fiction Stories 1800-1849 Science Fiction 37.59 One In stock ../media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg
19.  Libertarianism for Beginners Politics 51.33 Two In stock ../media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg
20.  It's Only the Himalayas Travel 45.17 Two In stock ../media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg
21.  In Her Wake Thriller 12.84 One In stock ../media/cache/5d/72/5d72709c6a7a9584a4d1cf07648bfce1.jpg
22.  How Music Works Music 37.32 Two In stock ../media/cache/5c/c8/5cc8e107246cb478960d4f0aba1e1c8e.jpg
23.  Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More Food and Drink 30.52 Three In stock ../media/cache/9f/59/9f59f01fa916a7bb8f0b28a4012179a4.jpg
24.  Chase Me (Paris Nights #2) Romance 25.27 Five In stock ../media/cache/9c/2e/9c2e0eb8866b8e3f3b768994fd3d1c1a.jpg
25.  Black Dust Romance 34.53 Five In stock ../media/cache/44/cc/44ccc99c8f82c33d4f9d2afa4ef25787.jpg
26.  Birdsong: A Story in Pictures Childrens 54.64 Three In stock ../media/cache/af/6e/af6e796160fe63e0cf19d44395c7ddf2.jpg
27.  America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana Default 22.50 Three In stock ../media/cache/ef/0b/ef0bed08de4e083dba5e20fdb98d9c36.jpg
28.  Aladdin and His Wonderful Lamp Default 53.13 Three In stock ../media/cache/d6/da/d6da0371958068bbaf39ea9c174275cd.jpg
29.  Worlds Elsewhere: Journeys Around Shakespeare’s Globe Nonfiction 40.30 Five In stock ../media/cache/2e/98/2e98c332bf8563b584784971541c4445.jpg
30.  Wall and Piece Art 44.18 Four In stock ../media/cache/a5/41/a5416b9646aaa7287baa287ec2590270.jpg
31.  The Four Agreements: A Practical Guide to Personal Freedom Spirituality 17.66 Five In stock ../media/cache/0f/7e/0f7ee69495c0df1d35723f012624a9f8.jpg
32.  The Five Love Languages: How to Express Heartfelt Commitment to Your Mate Nonfiction 31.05 Three In stock ../media/cache/38/c5/38c56fba316c07305643a8065269594e.jpg
33.  The Elephant Tree Thriller 23.82 Five In stock ../media/cache/5d/7e/5d7ecde8e81513eba8a64c9fe000744b.jpg
34.  The Bear and the Piano Childrens 36.89 One In stock ../media/cache/cf/bb/cfbb5e62715c6d888fd07794c9bab5d6.jpg
35.  Sophie's World Philosophy 15.94 Five In stock ../media/cache/65/71/6571919836ec51ed54f0050c31d8a0cd.jpg
36.  Penny Maybe Default 33.29 Three In stock ../media/cache/12/53/1253c21c5ef3c6d075c5fa3f5fecee6a.jpg
37.  Maude (1883-1993):She Grew Up with the country Default 18.02 Two In stock ../media/cache/f5/88/f5889d038f5d8e949b494d147c2dcf54.jpg
38.  In a Dark, Dark Wood Mystery 19.63 One In stock ../media/cache/23/85/238570a1c284e730dbc737a7e631ae2b.jpg
39.  Behind Closed Doors Thriller 52.22 Four In stock ../media/cache/e1/5c/e15c289ba58cea38519e1281e859f0c1.jpg
40.  You can't bury them all: Poems Poetry 33.63 Two In stock ../media/cache/e9/20/e9203b733126c4a0832a1c7885dc27cf.jpg
41.  Slow States of Collapse: Poems Poetry 57.31 Three In stock ../media/cache/72/41/72417db983862010ef0c1a25de98c7d7.jpg
42.  Reasons to Stay Alive Nonfiction 26.41 Two In stock ../media/cache/cb/bd/cbbdb0222ee8a0f6ab61657412a15794.jpg
43.  Private Paris (Private #10) Fiction 47.61 Five In stock ../media/cache/9d/05/9d0533bae1578846d728a82913b95c26.jpg
44.  #HigherSelfie: Wake Up Your Life. Free Your Soul. Find Your Tribe. Nonfiction 23.11 Five In stock ../media/cache/9c/46/9c463c7631c82401160fd3b554b8f0e1.jpg
45.  Without Borders (Wanderlove #1) New Adult 45.07 Two In stock ../media/cache/24/e2/24e2f5c9d325c4004d8190c054da86dd.jpg
46.  When We Collided Contemporary 31.77 One In stock ../media/cache/08/04/08044269fc197645268a6197c57e6173.jpg
47.  We Love You, Charlie Freeman Fiction 50.27 Five In stock ../media/cache/5f/15/5f152afdbc42356ecba02f61058a7e5b.jpg
48.  Untitled Collection: Sabbath Poems 2014 Poetry 14.27 Four In stock ../media/cache/f9/3b/f93b4a650f03a5d21f2436d7813f42c2.jpg
49.  Unseen City: The Majesty of Pigeons, the Discreet Charm of Snails & Other Wonders of the Urban Wilderness Nonfiction 44.18 Four In stock ../media/cache/41/a2/41a20f35adf0caea24f208dc01ad7681.jpg
50.  Unicorn Tracks Fantasy 18.78 Three In stock ../media/cache/76/8e/768ea5924ac1ef6297c2be9959c796c2.jpg
51.  Unbound: How Eight Technologies Made Us Human, Transformed Society, and Brought Our World to the Brink History 25.52 One In stock ../media/cache/4a/3b/4a3b055f9e378a95fedbef55e7bab7ce.jpg
52.  Tsubasa: WoRLD CHRoNiCLE 2 (Tsubasa WoRLD CHRoNiCLE #2) Sequential Art 16.28 One In stock ../media/cache/36/df/36df4caaf1420b1183a8235355d39e69.jpg
53.  Throwing Rocks at the Google Bus: How Growth Became the Enemy of Prosperity Nonfiction 31.12 Three In stock ../media/cache/03/86/038650c9e7517b4baf2a423cd8eed38f.jpg
54.  This One Summer Sequential Art 19.49 Four In stock ../media/cache/c4/dd/c4ddd9ced89966b0602ec85e00cd5b61.jpg
55.  Thirst Fiction 17.27 Five In stock ../media/cache/c4/0a/c40a64f59e7487b1a80a049f6ceb2ba5.jpg
56.  The Torch Is Passed: A Harding Family Story Add a comment 19.09 One In stock ../media/cache/33/e5/33e507172541628acfd421503196b578.jpg
57.  The Secret of Dreadwillow Carse Childrens 56.13 One In stock ../media/cache/c4/a2/c4a2a1a026c67bcceb5a411c724d7d0c.jpg
58.  The Pioneer Woman Cooks: Dinnertime: Comfort Classics, Freezer Food, 16-Minute Meals, and Other Delicious Ways to Solve Supper! Food and Drink 56.41 One In stock ../media/cache/b7/f4/b7f4843dbe062d44be1ffcfa16b2faa4.jpg
59.  The Past Never Ends Mystery 56.50 Four In stock ../media/cache/89/b8/89b850edb01851a91f64ba114b96acb6.jpg
60.  The Natural History of Us (The Fine Art of Pretending #2) Young Adult 45.22 Three In stock ../media/cache/5d/7f/5d7f496cdf5e5962a73ecdcc1505c1d5.jpg
61.  The Nameless City (The Nameless City #1) Sequential Art 38.16 Four In stock ../media/cache/f4/79/f479de5f305c2ac0512702cf7155bb74.jpg
62.  The Murder That Never Was (Forensic Instincts #5) Fiction 54.11 Three In stock ../media/cache/dc/44/dc44f8e2aebac48ca8553814d9b021a8.jpg
63.  The Most Perfect Thing: Inside (and Outside) a Bird's Egg Science 42.96 Four In stock ../media/cache/d4/8d/d48d5122a15347e9fe2b15ad354d69bf.jpg
64.  The Mindfulness and Acceptance Workbook for Anxiety: A Guide to Breaking Free from Anxiety, Phobias, and Worry Using Acceptance and Commitment Therapy Add a comment 23.89 Four In stock ../media/cache/f8/6d/f86d08178e3788563ac17be5aefd29f0.jpg
65.  The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing Nonfiction 16.77 Three In stock ../media/cache/95/64/95647d6a526bf54120b9445e124794e1.jpg
66.  The Inefficiency Assassin: Time Management Tactics for Working Smarter, Not Longer Default 20.59 Five In stock ../media/cache/75/dc/75dce2f5949b407161f37f0af249b018.jpg
67.  The Gutsy Girl: Escapades for Your Life of Epic Adventure Nonfiction 37.13 One In stock ../media/cache/64/15/641570cd7e7aded53c7d33d78a9629f1.jpg
68.  The Electric Pencil: Drawings from Inside State Hospital No. 3 Nonfiction 56.06 One In stock ../media/cache/2e/23/2e236e23ad52aa74505f224f6552eda8.jpg
69.  The Death of Humanity: and the Case for Life Philosophy 58.11 Four In stock ../media/cache/71/df/71df730cf38c232ee58a2e407135f055.jpg
70.  The Bulletproof Diet: Lose up to a Pound a Day, Reclaim Energy and Focus, Upgrade Your Life Health 49.05 Three In stock ../media/cache/ee/3e/ee3e219d23e73ba71c79b700f183aaed.jpg
71.  The Art Forger Add a comment 40.76 Three In stock ../media/cache/70/fa/70fa6c0437d9c97dbeada6bd32bf9d2c.jpg
72.  The Age of Genius: The Seventeenth Century and the Birth of the Modern Mind History 19.73 One In stock ../media/cache/2d/4e/2d4e358712e6c9f1d3bdd78d1a16e5a8.jpg
73.  The Activist's Tao Te Ching: Ancient Advice for a Modern Revolution Spirituality 32.24 Five In stock ../media/cache/96/db/96db61bb53930c560fb4c1c62b583816.jpg
74.  Spark Joy: An Illustrated Master Class on the Art of Organizing and Tidying Up Nonfiction 41.83 Four In stock ../media/cache/f3/4f/f34ffb24cc21c9f9f52dad4fd8f3ac21.jpg
75.  Soul Reader Default 39.58 Two In stock ../media/cache/69/85/69852567cf97264a1442cbc882c84903.jpg
76.  Security Horror 39.25 Two In stock ../media/cache/da/df/dadfac66a89774b46b10225362724c83.jpg
77.  Saga, Volume 6 (Saga (Collected Editions) #6) Fantasy 25.02 Three In stock ../media/cache/43/ae/43aee83ebb31e2122a7215e413770e5c.jpg
78.  Saga, Volume 5 (Saga (Collected Editions) #5) Sequential Art 51.04 Two In stock ../media/cache/e1/ea/e1ea6cb36e62ae6dc7b805f68ab9a700.jpg
79.  Reskilling America: Learning to Labor in the Twenty-First Century Nonfiction 19.83 Two In stock ../media/cache/97/f8/97f8debeeaaece9603267653076e760f.jpg
80.  Rat Queens, Vol. 3: Demons (Rat Queens (Collected Editions) #11-15) Sequential Art 50.40 Three In stock ../media/cache/f3/ef/f3efd43ae0fa85d9b325d5e8783e7af5.jpg
81.  Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jellyfish 2-in-1 Omnibus #1) Sequential Art 13.61 Five In stock ../media/cache/78/0b/780b2c28122750c2c383846155815bf7.jpg
82.  Princess Between Worlds (Wide-Awake Princess #5) Fantasy 13.34 Five In stock ../media/cache/b7/e8/b7e84b78be3d9bb79b71156a5e5d4e42.jpg
83.  Pop Gun War, Volume 1: Gift Sequential Art 18.97 One In stock ../media/cache/c8/2f/c82f629a31b3f47bdb17ac14aa51076d.jpg
84.  Political Suicide: Missteps, Peccadilloes, Bad Calls, Backroom Hijinx, Sordid Pasts, Rotten Breaks, and Just Plain Dumb Mistakes in the Annals of American Politics History 36.28 Two In stock ../media/cache/64/44/6444dacdcb9edaadbbd691524622aeb8.jpg
85.  Patience Sequential Art 10.16 Three In stock ../media/cache/01/72/01726c619a05114dca75bd840095016d.jpg
86.  Outcast, Vol. 1: A Darkness Surrounds Him (Outcast #1) Sequential Art 15.44 Four In stock ../media/cache/cb/00/cb004189f548d75ad430d3ed19e6daa9.jpg
87.  orange: The Complete Collection 1 (orange: The Complete Collection #1) Sequential Art 48.41 One In stock ../media/cache/03/88/03886a8502ca54dbce0d91c2568ab69d.jpg
88.  Online Marketing for Busy Authors: A Step-By-Step Guide Self Help 46.35 One In stock ../media/cache/ea/9b/ea9b2cb8abbb317402e618445bade1e1.jpg
89.  On a Midnight Clear Add a comment 14.07 Three In stock ../media/cache/a1/14/a114d70e7babf110ba42a389078e9a45.jpg
90.  Obsidian (Lux #1) Young Adult 14.86 Two In stock ../media/cache/fc/72/fc72f158554b4b4164701e1dfa1153c7.jpg
91.  My Paris Kitchen: Recipes and Stories Food and Drink 33.37 Two In stock ../media/cache/f5/65/f565af3d9dd20a1ad72a1e7c4157387d.jpg
92.  Masks and Shadows Fantasy 56.40 Two In stock ../media/cache/ff/e8/ffe81bf98f8386ef29e193abfb6f9c1e.jpg
93.  Mama Tried: Traditional Italian Cooking for the Screwed, Crude, Vegan, and Tattooed Food and Drink 14.02 Four In stock ../media/cache/10/c6/10c61093002db1fec4089d8076678624.jpg
94.  Lumberjanes, Vol. 2: Friendship to the Max (Lumberjanes #5-8) Sequential Art 46.91 Two In stock ../media/cache/d3/15/d3158e8d3546fb90cced3c1d44a92a34.jpg
95.  Lumberjanes, Vol. 1: Beware the Kitten Holy (Lumberjanes #1-4) Sequential Art 45.61 Three In stock ../media/cache/7e/a0/7ea062007ef00107e3c16d336b41fab2.jpg
96.  Lumberjanes Vol. 3: A Terrible Plan (Lumberjanes #9-12) Sequential Art 19.92 Two In stock ../media/cache/5f/b1/5fb1bf88dcfda795606745ce35be5975.jpg
97.  Layered: Baking, Building, and Styling Spectacular Cakes Food and Drink 40.11 One In stock ../media/cache/98/d1/98d1c979c4bac9e147a6718946578b0f.jpg
98.  Judo: Seven Steps to Black Belt (an Introductory Guide for Beginners) Add a comment 53.90 Two In stock ../media/cache/5f/52/5f52b1bc6d45daab2e330c744feb0359.jpg
99.  Join Science Fiction 35.67 Five In stock ../media/cache/93/63/9363f0065fbad5689f44fcf6e203eef3.jpg
100.  In the Country We Love: My Family Divided Nonfiction 22.00 Four In stock ../media/cache/fe/ea/feeafd2ad7b3077f8e74cbb1da9e3c7d.jpg
101.  Immunity: How Elie Metchnikoff Changed the Course of Modern Medicine Science 57.36 Five In stock ../media/cache/26/1c/261c4eaf957ae4aacf2229b482e76dbe.jpg
102.  I Hate Fairyland, Vol. 1: Madly Ever After (I Hate Fairyland (Compilations) #1-5) Sequential Art 29.17 Two In stock ../media/cache/aa/74/aa74004807e97a79aa084b5db329a99b.jpg
103.  I am a Hero Omnibus Volume 1 Sequential Art 54.63 Three In stock ../media/cache/16/d4/16d443437126bf6d536a89312c1995a5.jpg
104.  How to Be Miserable: 40 Strategies You Already Use Self Help 46.03 One In stock ../media/cache/da/8b/da8bc9b824dd3f446ef63e438ddbfc85.jpg
105.  Her Backup Boyfriend (The Sorensen Family #1) Romance 33.97 One In stock ../media/cache/1e/bb/1ebbbc3e2d3249b111033cfc40763b0b.jpg
106.  Giant Days, Vol. 2 (Giant Days #5-8) Sequential Art 22.11 Two In stock ../media/cache/90/6f/906f0168b0e155a7077625499b1737b5.jpg
107.  Forever and Forever: The Courtship of Henry Longfellow and Fanny Appleton Historical Fiction 29.69 Three In stock ../media/cache/d6/58/d658a1485b130ff26ca5fb0d5975ed2e.jpg
108.  First and First (Five Boroughs #3) Romance 15.97 Four In stock ../media/cache/c4/d1/c4d1517cc9370e292366b6132ca9ca36.jpg
109.  Fifty Shades Darker (Fifty Shades #2) Romance 21.96 One In stock ../media/cache/cc/bd/ccbdae9e29b3594301528fa2c876ec29.jpg
110.  Everydata: The Misinformation Hidden in the Little Data You Consume Every Day Nonfiction 54.35 Two In stock ../media/cache/64/94/6494bf61176ca73b61255909230030be.jpg
111.  Don't Be a Jerk: And Other Practical Advice from Dogen, Japan's Greatest Zen Master Religion 37.97 Two In stock ../media/cache/95/30/953013d044aa313cc162dec414f3969a.jpg
112.  Danganronpa Volume 1 Sequential Art 51.99 Four In stock ../media/cache/78/97/7897eea91c4a85aca58d925861d4afec.jpg
113.  Crown of Midnight (Throne of Glass #2) Fantasy 43.29 Three In stock ../media/cache/66/25/6625e3bbb050de3e42a0c302c0d69f1f.jpg
114.  Codename Baboushka, Volume 1: The Conclave of Death Sequential Art 36.72 Four In stock ../media/cache/f6/88/f688a9d6a89fdf38e4e88439ee9eda69.jpg
115.  Camp Midnight Sequential Art 17.08 Four In stock ../media/cache/dd/c9/ddc95df6754df8e71bf969c088056188.jpg
116.  Call the Nurse: True Stories of a Country Nurse on a Scottish Isle Nonfiction 29.14 Five In stock ../media/cache/88/9e/889e0bac4c7c0e7178f0165b8d3b4617.jpg
117.  Burning Young Adult 28.81 Three In stock ../media/cache/26/95/269507c7bb35d2cec9b61a03d1c28e67.jpg
118.  Bossypants Default 49.46 Two In stock ../media/cache/27/d2/27d20361745ec2f7be668b18a4da29da.jpg
119.  Bitch Planet, Vol. 1: Extraordinary Machine (Bitch Planet (Collected Editions)) Sequential Art 37.92 Two In stock ../media/cache/e4/1d/e41d34204a1fffbf825d8beb3dbf4cbc.jpg
120.  Avatar: The Last Airbender: Smoke and Shadow, Part 3 (Smoke and Shadow #3) Fantasy 28.09 Two In stock ../media/cache/06/18/061811c5845d0e13bc04b2a755f0830f.jpg
121.  Algorithms to Live By: The Computer Science of Human Decisions Nonfiction 30.81 One In stock ../media/cache/23/b4/23b42e094c02d52b14b11a960d49610e.jpg
122.  A World of Flavor: Your Gluten Free Passport Default 42.95 One In stock ../media/cache/78/2e/782e315667ec50759b8603527ee33dec.jpg
123.  A Piece of Sky, a Grain of Rice: A Memoir in Four Meditations Default 56.76 Five In stock ../media/cache/08/89/088995e862aac86c88c608d763f6390e.jpg
124.  A Murder in Time Mystery 16.64 One In stock ../media/cache/11/aa/11aaad48b5f15e262456ca65294084da.jpg
125.  A Flight of Arrows (The Pathfinders #2) Historical Fiction 55.53 Five In stock ../media/cache/82/96/8296f92b70fb1dafefecda92c1d51941.jpg
126.  A Fierce and Subtle Poison Young Adult 28.13 Four In stock ../media/cache/12/f1/12f1963957f27fa83d51f76b183ef490.jpg
127.  A Court of Thorns and Roses (A Court of Thorns and Roses #1) Fantasy 52.37 One In stock ../media/cache/c0/88/c08816960890396213a423941af65b8f.jpg
128.  (Un)Qualified: How God Uses Broken People to Do Big Things Christian 54.00 Five In stock ../media/cache/cd/db/cddb3eb483ef11a088d519205b7098fb.jpg
129.  You Are What You Love: The Spiritual Power of Habit Religion 21.87 Four In stock ../media/cache/6b/70/6b70f2cdb17d9ab7551240a88b9211fe.jpg
130.  William Shakespeare's Star Wars: Verily, A New Hope (William Shakespeare's Star Wars #4) Science Fiction 43.30 Four In stock ../media/cache/02/37/0237b445efc18c5562355a5a2c40889c.jpg
131.  Tuesday Nights in 1980 Fiction 21.04 Two In stock ../media/cache/6b/da/6bdae061cb92c32b0b83cda8dd10275d.jpg
132.  Tracing Numbers on a Train Default 41.60 Three In stock ../media/cache/06/a6/06a6cfcf89afd1601cbba1a16cda57fb.jpg
133.  Throne of Glass (Throne of Glass #1) Fantasy 35.07 Three In stock ../media/cache/32/d6/32d6aa560e8ddf2a4da1526b95d4c7ab.jpg
134.  Thomas Jefferson and the Tripoli Pirates: The Forgotten War That Changed American History History 59.64 One In stock ../media/cache/97/47/974709d437b08e74649b5744471bf472.jpg
135.  Thirteen Reasons Why Default 52.72 One In stock ../media/cache/8a/83/8a83b6ce350f01bab21f85e6ba539316.jpg
136.  The White Cat and the Monk: A Retelling of the Poem “Pangur Bán” Childrens 58.08 Four In stock ../media/cache/26/32/2632a1e12f2c085fabbe022ae4cd6933.jpg
137.  The Wedding Dress Romance 24.12 One In stock ../media/cache/28/99/28992d89f4abf54fba183fc8d074adf3.jpg
138.  The Vacationers Fiction 42.15 Four In stock ../media/cache/37/25/372578cc073efae80cf284b56040a488.jpg
139.  The Third Wave: An Entrepreneur’s Vision of the Future Business 12.61 Five In stock ../media/cache/d0/77/d077a30042df6b916bfc8d257345c69e.jpg
140.  The Stranger Philosophy 17.44 Four In stock ../media/cache/ea/04/ea0476a6f4c318ceccf5e2f2b39f2b15.jpg
141.  The Shadow Hero (The Shadow Hero) Sequential Art 33.14 One In stock ../media/cache/1f/62/1f621dda1b302fc16d83d94b0b5ac31c.jpg
142.  The Secret (The Secret #1) Default 27.37 Four In stock ../media/cache/4e/0f/4e0f05ae01d8fb6bd0d3901edd06de16.jpg

In [19]:
books_data

[{'title': 'A Light in the Attic',
  'category': 'Poetry',
  'price': 51.77,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg'},
 {'title': 'Tipping the Velvet',
  'category': 'Historical Fiction',
  'price': 53.74,
  'rating': 'One',
  'availability': 'In stock',
  'image_url': '../media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg'},
 {'title': 'Soumission',
  'category': 'Fiction',
  'price': 50.1,
  'rating': 'One',
  'availability': 'In stock',
  'image_url': '../media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg'},
 {'title': 'Sharp Objects',
  'category': 'Mystery',
  'price': 47.82,
  'rating': 'Four',
  'availability': 'In stock',
  'image_url': '../media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg'},
 {'title': 'Sapiens: A Brief History of Humankind',
  'category': 'History',
  'price': 54.23,
  'rating': 'Five',
  'availability': 'In stock',
  'image_url': '../media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg'},
 {'title': 'The Requiem Red',
  'category': 'Young Adult',
  'price': 22.65,
  'rating': 'One',
  'availability': 'In stock',
  'image_url': '../media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg'},
 {'title': 'The Dirty Little Secrets of Getting Your Dream Job',
  'category': 'Business',
  'price': 33.34,
  'rating': 'Four',
  'availability': 'In stock',
  'image_url': '../media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg'},
 {'title': 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull',
  'category': 'Default',
  'price': 17.93,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg'},
 {'title': 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics',
  'category': 'Default',
  'price': 22.6,
  'rating': 'Four',
  'availability': 'In stock',
  'image_url': '../media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg'},
 {'title': 'The Black Maria',
  'category': 'Poetry',
  'price': 52.15,
  'rating': 'One',
  'availability': 'In stock',
  'image_url': '../media/cache/58/46/5846057e28022268153beff6d352b06c.jpg'},
 {'title': 'Starving Hearts (Triangular Trade Trilogy, #1)',
  'category': 'Default',
  'price': 13.99,
  'rating': 'Two',
  'availability': 'In stock',
  'image_url': '../media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg'},
 {'title': "Shakespeare's Sonnets",
  'category': 'Poetry',
  'price': 20.66,
  'rating': 'Four',
  'availability': 'In stock',
  'image_url': '../media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg'},
 {'title': 'Set Me Free',
  'category': 'Young Adult',
  'price': 17.46,
  'rating': 'Five',
  'availability': 'In stock',
  'image_url': '../media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg'},
 {'title': "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)",
  'category': 'Sequential Art',
  'price': 52.29,
  'rating': 'Five',
  'availability': 'In stock',
  'image_url': '../media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg'},
 {'title': 'Rip it Up and Start Again',
  'category': 'Music',
  'price': 35.02,
  'rating': 'Five',
  'availability': 'In stock',
  'image_url': '../media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg'},
 {'title': 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991',
  'category': 'Music',
  'price': 57.25,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg'},
 {'title': 'Olio',
  'category': 'Poetry',
  'price': 23.88,
  'rating': 'One',
  'availability': 'In stock',
  'image_url': '../media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg'},
 {'title': 'Mesaerion: The Best Science Fiction Stories 1800-1849',
  'category': 'Science Fiction',
  'price': 37.59,
  'rating': 'One',
  'availability': 'In stock',
  'image_url': '../media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg'},
 {'title': 'Libertarianism for Beginners',
  'category': 'Politics',
  'price': 51.33,
  'rating': 'Two',
  'availability': 'In stock',
  'image_url': '../media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg'},
 {'title': "It's Only the Himalayas",
  'category': 'Travel',
  'price': 45.17,
  'rating': 'Two',
  'availability': 'In stock',
  'image_url': '../media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg'},
 {'title': 'In Her Wake',
  'category': 'Thriller',
  'price': 12.84,
  'rating': 'One',
  'availability': 'In stock',
  'image_url': '../media/cache/5d/72/5d72709c6a7a9584a4d1cf07648bfce1.jpg'},
 {'title': 'How Music Works',
  'category': 'Music',
  'price': 37.32,
  'rating': 'Two',
  'availability': 'In stock',
  'image_url': '../media/cache/5c/c8/5cc8e107246cb478960d4f0aba1e1c8e.jpg'},
 {'title': 'Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More',
  'category': 'Food and Drink',
  'price': 30.52,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/9f/59/9f59f01fa916a7bb8f0b28a4012179a4.jpg'},
 {'title': 'Chase Me (Paris Nights #2)',
  'category': 'Romance',
  'price': 25.27,
  'rating': 'Five',
  'availability': 'In stock',
  'image_url': '../media/cache/9c/2e/9c2e0eb8866b8e3f3b768994fd3d1c1a.jpg'},
 {'title': 'Black Dust',
  'category': 'Romance',
  'price': 34.53,
  'rating': 'Five',
  'availability': 'In stock',
  'image_url': '../media/cache/44/cc/44ccc99c8f82c33d4f9d2afa4ef25787.jpg'},
 {'title': 'Birdsong: A Story in Pictures',
  'category': 'Childrens',
  'price': 54.64,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/af/6e/af6e796160fe63e0cf19d44395c7ddf2.jpg'},
 {'title': "America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana",
  'category': 'Default',
  'price': 22.5,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/ef/0b/ef0bed08de4e083dba5e20fdb98d9c36.jpg'},
 {'title': 'Aladdin and His Wonderful Lamp',
  'category': 'Default',
  'price': 53.13,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/d6/da/d6da0371958068bbaf39ea9c174275cd.jpg'},
 {'title': 'Worlds Elsewhere: Journeys Around Shakespeare’s Globe',
  'category': 'Nonfiction',
  'price': 40.3,
  'rating': 'Five',
  'availability': 'In stock',
  'image_url': '../media/cache/2e/98/2e98c332bf8563b584784971541c4445.jpg'},
 {'title': 'Wall and Piece',
  'category': 'Art',
  'price': 44.18,
  'rating': 'Four',
  'availability': 'In stock',
  'image_url': '../media/cache/a5/41/a5416b9646aaa7287baa287ec2590270.jpg'},
 {'title': 'The Four Agreements: A Practical Guide to Personal Freedom',
  'category': 'Spirituality',
  'price': 17.66,
  'rating': 'Five',
  'availability': 'In stock',
  'image_url': '../media/cache/0f/7e/0f7ee69495c0df1d35723f012624a9f8.jpg'},
 {'title': 'The Five Love Languages: How to Express Heartfelt Commitment to Your Mate',
  'category': 'Nonfiction',
  'price': 31.05,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/38/c5/38c56fba316c07305643a8065269594e.jpg'},
 {'title': 'The Elephant Tree',
  'category': 'Thriller',
  'price': 23.82,
  'rating': 'Five',
  'availability': 'In stock',
  'image_url': '../media/cache/5d/7e/5d7ecde8e81513eba8a64c9fe000744b.jpg'},
 {'title': 'The Bear and the Piano',
  'category': 'Childrens',
  'price': 36.89,
  'rating': 'One',
  'availability': 'In stock',
  'image_url': '../media/cache/cf/bb/cfbb5e62715c6d888fd07794c9bab5d6.jpg'},
 {'title': "Sophie's World",
  'category': 'Philosophy',
  'price': 15.94,
  'rating': 'Five',
  'availability': 'In stock',
  'image_url': '../media/cache/65/71/6571919836ec51ed54f0050c31d8a0cd.jpg'},
 {'title': 'Penny Maybe',
  'category': 'Default',
  'price': 33.29,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/12/53/1253c21c5ef3c6d075c5fa3f5fecee6a.jpg'},
 {'title': 'Maude (1883-1993):She Grew Up with the country',
  'category': 'Default',
  'price': 18.02,
  'rating': 'Two',
  'availability': 'In stock',
  'image_url': '../media/cache/f5/88/f5889d038f5d8e949b494d147c2dcf54.jpg'},
 {'title': 'In a Dark, Dark Wood',
  'category': 'Mystery',
  'price': 19.63,
  'rating': 'One',
  'availability': 'In stock',
  'image_url': '../media/cache/23/85/238570a1c284e730dbc737a7e631ae2b.jpg'},
 {'title': 'Behind Closed Doors',
  'category': 'Thriller',
  'price': 52.22,
  'rating': 'Four',
  'availability': 'In stock',
  'image_url': '../media/cache/e1/5c/e15c289ba58cea38519e1281e859f0c1.jpg'},
 {'title': "You can't bury them all: Poems",
  'category': 'Poetry',
  'price': 33.63,
  'rating': 'Two',
  'availability': 'In stock',
  'image_url': '../media/cache/e9/20/e9203b733126c4a0832a1c7885dc27cf.jpg'},
 {'title': 'Slow States of Collapse: Poems',
  'category': 'Poetry',
  'price': 57.31,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/72/41/72417db983862010ef0c1a25de98c7d7.jpg'},
 {'title': 'Reasons to Stay Alive',
  'category': 'Nonfiction',
  'price': 26.41,
  'rating': 'Two',
  'availability': 'In stock',
  'image_url': '../media/cache/cb/bd/cbbdb0222ee8a0f6ab61657412a15794.jpg'},
 {'title': 'Private Paris (Private #10)',
  'category': 'Fiction',
  'price': 47.61,
  'rating': 'Five',
  'availability': 'In stock',
  'image_url': '../media/cache/9d/05/9d0533bae1578846d728a82913b95c26.jpg'},
 {'title': '#HigherSelfie: Wake Up Your Life. Free Your Soul. Find Your Tribe.',
  'category': 'Nonfiction',
  'price': 23.11,
  'rating': 'Five',
  'availability': 'In stock',
  'image_url': '../media/cache/9c/46/9c463c7631c82401160fd3b554b8f0e1.jpg'},
 {'title': 'Without Borders (Wanderlove #1)',
  'category': 'New Adult',
  'price': 45.07,
  'rating': 'Two',
  'availability': 'In stock',
  'image_url': '../media/cache/24/e2/24e2f5c9d325c4004d8190c054da86dd.jpg'},
 {'title': 'When We Collided',
  'category': 'Contemporary',
  'price': 31.77,
  'rating': 'One',
  'availability': 'In stock',
  'image_url': '../media/cache/08/04/08044269fc197645268a6197c57e6173.jpg'},
 {'title': 'We Love You, Charlie Freeman',
  'category': 'Fiction',
  'price': 50.27,
  'rating': 'Five',
  'availability': 'In stock',
  'image_url': '../media/cache/5f/15/5f152afdbc42356ecba02f61058a7e5b.jpg'},
 {'title': 'Untitled Collection: Sabbath Poems 2014',
  'category': 'Poetry',
  'price': 14.27,
  'rating': 'Four',
  'availability': 'In stock',
  'image_url': '../media/cache/f9/3b/f93b4a650f03a5d21f2436d7813f42c2.jpg'},
 {'title': 'Unseen City: The Majesty of Pigeons, the Discreet Charm of Snails & Other Wonders of the Urban Wilderness',
  'category': 'Nonfiction',
  'price': 44.18,
  'rating': 'Four',
  'availability': 'In stock',
  'image_url': '../media/cache/41/a2/41a20f35adf0caea24f208dc01ad7681.jpg'},
 {'title': 'Unicorn Tracks',
  'category': 'Fantasy',
  'price': 18.78,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/76/8e/768ea5924ac1ef6297c2be9959c796c2.jpg'},
 {'title': 'Unbound: How Eight Technologies Made Us Human, Transformed Society, and Brought Our World to the Brink',
  'category': 'History',
  'price': 25.52,
  'rating': 'One',
  'availability': 'In stock',
  'image_url': '../media/cache/4a/3b/4a3b055f9e378a95fedbef55e7bab7ce.jpg'},
 {'title': 'Tsubasa: WoRLD CHRoNiCLE 2 (Tsubasa WoRLD CHRoNiCLE #2)',
  'category': 'Sequential Art',
  'price': 16.28,
  'rating': 'One',
  'availability': 'In stock',
  'image_url': '../media/cache/36/df/36df4caaf1420b1183a8235355d39e69.jpg'},
 {'title': 'Throwing Rocks at the Google Bus: How Growth Became the Enemy of Prosperity',
  'category': 'Nonfiction',
  'price': 31.12,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/03/86/038650c9e7517b4baf2a423cd8eed38f.jpg'},
 {'title': 'This One Summer',
  'category': 'Sequential Art',
  'price': 19.49,
  'rating': 'Four',
  'availability': 'In stock',
  'image_url': '../media/cache/c4/dd/c4ddd9ced89966b0602ec85e00cd5b61.jpg'},
 {'title': 'Thirst',
  'category': 'Fiction',
  'price': 17.27,
  'rating': 'Five',
  'availability': 'In stock',
  'image_url': '../media/cache/c4/0a/c40a64f59e7487b1a80a049f6ceb2ba5.jpg'},
 {'title': 'The Torch Is Passed: A Harding Family Story',
  'category': 'Add a comment',
  'price': 19.09,
  'rating': 'One',
  'availability': 'In stock',
  'image_url': '../media/cache/33/e5/33e507172541628acfd421503196b578.jpg'},
 {'title': 'The Secret of Dreadwillow Carse',
  'category': 'Childrens',
  'price': 56.13,
  'rating': 'One',
  'availability': 'In stock',
  'image_url': '../media/cache/c4/a2/c4a2a1a026c67bcceb5a411c724d7d0c.jpg'},
 {'title': 'The Pioneer Woman Cooks: Dinnertime: Comfort Classics, Freezer Food, 16-Minute Meals, and Other Delicious Ways to Solve Supper!',
  'category': 'Food and Drink',
  'price': 56.41,
  'rating': 'One',
  'availability': 'In stock',
  'image_url': '../media/cache/b7/f4/b7f4843dbe062d44be1ffcfa16b2faa4.jpg'},
 {'title': 'The Past Never Ends',
  'category': 'Mystery',
  'price': 56.5,
  'rating': 'Four',
  'availability': 'In stock',
  'image_url': '../media/cache/89/b8/89b850edb01851a91f64ba114b96acb6.jpg'},
 {'title': 'The Natural History of Us (The Fine Art of Pretending #2)',
  'category': 'Young Adult',
  'price': 45.22,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/5d/7f/5d7f496cdf5e5962a73ecdcc1505c1d5.jpg'},
 {'title': 'The Nameless City (The Nameless City #1)',
  'category': 'Sequential Art',
  'price': 38.16,
  'rating': 'Four',
  'availability': 'In stock',
  'image_url': '../media/cache/f4/79/f479de5f305c2ac0512702cf7155bb74.jpg'},
 {'title': 'The Murder That Never Was (Forensic Instincts #5)',
  'category': 'Fiction',
  'price': 54.11,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/dc/44/dc44f8e2aebac48ca8553814d9b021a8.jpg'},
 {'title': "The Most Perfect Thing: Inside (and Outside) a Bird's Egg",
  'category': 'Science',
  'price': 42.96,
  'rating': 'Four',
  'availability': 'In stock',
  'image_url': '../media/cache/d4/8d/d48d5122a15347e9fe2b15ad354d69bf.jpg'},
 {'title': 'The Mindfulness and Acceptance Workbook for Anxiety: A Guide to Breaking Free from Anxiety, Phobias, and Worry Using Acceptance and Commitment Therapy',
  'category': 'Add a comment',
  'price': 23.89,
  'rating': 'Four',
  'availability': 'In stock',
  'image_url': '../media/cache/f8/6d/f86d08178e3788563ac17be5aefd29f0.jpg'},
 {'title': 'The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing',
  'category': 'Nonfiction',
  'price': 16.77,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/95/64/95647d6a526bf54120b9445e124794e1.jpg'},
 {'title': 'The Inefficiency Assassin: Time Management Tactics for Working Smarter, Not Longer',
  'category': 'Default',
  'price': 20.59,
  'rating': 'Five',
  'availability': 'In stock',
  'image_url': '../media/cache/75/dc/75dce2f5949b407161f37f0af249b018.jpg'},
 {'title': 'The Gutsy Girl: Escapades for Your Life of Epic Adventure',
  'category': 'Nonfiction',
  'price': 37.13,
  'rating': 'One',
  'availability': 'In stock',
  'image_url': '../media/cache/64/15/641570cd7e7aded53c7d33d78a9629f1.jpg'},
 {'title': 'The Electric Pencil: Drawings from Inside State Hospital No. 3',
  'category': 'Nonfiction',
  'price': 56.06,
  'rating': 'One',
  'availability': 'In stock',
  'image_url': '../media/cache/2e/23/2e236e23ad52aa74505f224f6552eda8.jpg'},
 {'title': 'The Death of Humanity: and the Case for Life',
  'category': 'Philosophy',
  'price': 58.11,
  'rating': 'Four',
  'availability': 'In stock',
  'image_url': '../media/cache/71/df/71df730cf38c232ee58a2e407135f055.jpg'},
 {'title': 'The Bulletproof Diet: Lose up to a Pound a Day, Reclaim Energy and Focus, Upgrade Your Life',
  'category': 'Health',
  'price': 49.05,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/ee/3e/ee3e219d23e73ba71c79b700f183aaed.jpg'},
 {'title': 'The Art Forger',
  'category': 'Add a comment',
  'price': 40.76,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/70/fa/70fa6c0437d9c97dbeada6bd32bf9d2c.jpg'},
 {'title': 'The Age of Genius: The Seventeenth Century and the Birth of the Modern Mind',
  'category': 'History',
  'price': 19.73,
  'rating': 'One',
  'availability': 'In stock',
  'image_url': '../media/cache/2d/4e/2d4e358712e6c9f1d3bdd78d1a16e5a8.jpg'},
 {'title': "The Activist's Tao Te Ching: Ancient Advice for a Modern Revolution",
  'category': 'Spirituality',
  'price': 32.24,
  'rating': 'Five',
  'availability': 'In stock',
  'image_url': '../media/cache/96/db/96db61bb53930c560fb4c1c62b583816.jpg'},
 {'title': 'Spark Joy: An Illustrated Master Class on the Art of Organizing and Tidying Up',
  'category': 'Nonfiction',
  'price': 41.83,
  'rating': 'Four',
  'availability': 'In stock',
  'image_url': '../media/cache/f3/4f/f34ffb24cc21c9f9f52dad4fd8f3ac21.jpg'},
 {'title': 'Soul Reader',
  'category': 'Default',
  'price': 39.58,
  'rating': 'Two',
  'availability': 'In stock',
  'image_url': '../media/cache/69/85/69852567cf97264a1442cbc882c84903.jpg'},
 {'title': 'Security',
  'category': 'Horror',
  'price': 39.25,
  'rating': 'Two',
  'availability': 'In stock',
  'image_url': '../media/cache/da/df/dadfac66a89774b46b10225362724c83.jpg'},
 {'title': 'Saga, Volume 6 (Saga (Collected Editions) #6)',
  'category': 'Fantasy',
  'price': 25.02,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/43/ae/43aee83ebb31e2122a7215e413770e5c.jpg'},
 {'title': 'Saga, Volume 5 (Saga (Collected Editions) #5)',
  'category': 'Sequential Art',
  'price': 51.04,
  'rating': 'Two',
  'availability': 'In stock',
  'image_url': '../media/cache/e1/ea/e1ea6cb36e62ae6dc7b805f68ab9a700.jpg'},
 {'title': 'Reskilling America: Learning to Labor in the Twenty-First Century',
  'category': 'Nonfiction',
  'price': 19.83,
  'rating': 'Two',
  'availability': 'In stock',
  'image_url': '../media/cache/97/f8/97f8debeeaaece9603267653076e760f.jpg'},
 {'title': 'Rat Queens, Vol. 3: Demons (Rat Queens (Collected Editions) #11-15)',
  'category': 'Sequential Art',
  'price': 50.4,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/f3/ef/f3efd43ae0fa85d9b325d5e8783e7af5.jpg'},
 {'title': 'Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jellyfish 2-in-1 Omnibus #1)',
  'category': 'Sequential Art',
  'price': 13.61,
  'rating': 'Five',
  'availability': 'In stock',
  'image_url': '../media/cache/78/0b/780b2c28122750c2c383846155815bf7.jpg'},
 {'title': 'Princess Between Worlds (Wide-Awake Princess #5)',
  'category': 'Fantasy',
  'price': 13.34,
  'rating': 'Five',
  'availability': 'In stock',
  'image_url': '../media/cache/b7/e8/b7e84b78be3d9bb79b71156a5e5d4e42.jpg'},
 {'title': 'Pop Gun War, Volume 1: Gift',
  'category': 'Sequential Art',
  'price': 18.97,
  'rating': 'One',
  'availability': 'In stock',
  'image_url': '../media/cache/c8/2f/c82f629a31b3f47bdb17ac14aa51076d.jpg'},
 {'title': 'Political Suicide: Missteps, Peccadilloes, Bad Calls, Backroom Hijinx, Sordid Pasts, Rotten Breaks, and Just Plain Dumb Mistakes in the Annals of American Politics',
  'category': 'History',
  'price': 36.28,
  'rating': 'Two',
  'availability': 'In stock',
  'image_url': '../media/cache/64/44/6444dacdcb9edaadbbd691524622aeb8.jpg'},
 {'title': 'Patience',
  'category': 'Sequential Art',
  'price': 10.16,
  'rating': 'Three',
  'availability': 'In stock',
  'image_url': '../media/cache/01/72/01726c619a05114dca75bd840095016d.jpg'},
 {'title': 'Outcast, Vol. 1: A Darkness Surrounds Him (Outcast #1)',
  'category': 'Sequential Art',
  'price': 15.44,
  'rating': 'Four',
  'availability': 'In stock',